language: node_js
node_js: 14.17.6

cache:
  directories:
    - node_modules
stages:
  - test
  - deploy

install:
  - npm ci
jobs:
  include:
    - stage: test
      if: branch = main
      script:
        - npm run test
      deploy:
        provider: heroku
        api_key:
          secure: $HEROKU_API_KEY
        app: yas-financial-times
    - stage: deploy
      if: type = push
      script:
        - npm run test
        - npm run validate-loc
      deploy:
        provider: heroku
        api_key:
          secure: $HEROKU_API_KEY
        app: yas-financial-times
